### ISSUE TITLE
编译py36-pytorch0.4.0-cu90-ctc出错

### ISSUE THREAD

**Issue by xwzheng1020** [Leinao/LeinaoPAI#14]
Installed /opt/conda/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg
Processing dependencies for warpctc-pytorch==0.1
Finished processing dependencies for warpctc-pytorch==0.1
Cloning into '/usr/local/ctcdecode'...
Submodule 'third_party/ThreadPool' (https://github.com/progschj/ThreadPool.git) registered for path 'third_party/ThreadPool'
Submodule 'third_party/kenlm' (https://github.com/kpu/kenlm.git) registered for path 'third_party/kenlm'
Cloning into 'third_party/ThreadPool'...
Submodule path 'third_party/ThreadPool': checked out '9a42ec1329f259a5f4881a291db1dcb8f2ad9040'
Cloning into 'third_party/kenlm'...
Submodule path 'third_party/kenlm': checked out '35835f1ac4884126458ac89f9bf6dd9ccad561e0'
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /usr/local/ctcdecode
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-req-build-xx9mzxel/.eggs/wget-3.2-py3.6.egg
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/opt/conda/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/opt/conda/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/opt/conda/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/opt/conda/lib/python3.6/http/client.py", line 1392, in connect
        super().connect()
      File "/opt/conda/lib/python3.6/http/client.py", line 936, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/opt/conda/lib/python3.6/socket.py", line 724, in create_connection
        raise err
      File "/opt/conda/lib/python3.6/socket.py", line 713, in create_connection
        sock.connect(sa)
    TimeoutError: [Errno 110] Connection timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xx9mzxel/setup.py", line 55, in <module>
        os.path.join(this_file, "build.py:ffi")
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/opt/conda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 204, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/opt/conda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/opt/conda/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "/tmp/pip-req-build-xx9mzxel/build.py", line 26, in <module>
        'third_party/openfst-1.6.7.tar.gz')
      File "/tmp/pip-req-build-xx9mzxel/build.py", line 15, in download_extract
        wget.download(url, out=dl_path)
      File "/tmp/pip-req-build-xx9mzxel/.eggs/wget-3.2-py3.6.egg/wget.py", line 526, in download
      File "/opt/conda/lib/python3.6/urllib/request.py", line 248, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
      File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/opt/conda/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-xx9mzxel/

**Comment by Rhythmblue** [comment]
这个错误发生在一个库的代码中，下载文件超时，我已调整该库。
现在麻烦重新build一下，还是用原来的dockerfile，谢谢~

**Comment by Rhythmblue** [comment]
可以使用了，辛苦~
